name: 자동화 파이썬 실행하기

on:
  schedule:
    - cron: '30 23 * * *'  # UTC 23:30 (한국 시간 08:30)
  workflow_dispatch:  # 수동 실행 가능

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client pandas requests beautifulsoup4
    
    - name: Create credentials file
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > google_credentials.json
    
    - name: Run crawler
      run: python crawler.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
