name: 자동화 파이썬 실행하기

on:
  schedule:
    - cron: '30 8 * * *'  # 매일 오전 8시 30분
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          pip install -r requirements.txt
          python read_the_sheet.py
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIAL }}  # <-- 이 부분이 꼭 있어야 해!
